# Copyright (c) 2025-now by the Zeek Project. See LICENSE for details.
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v20.1.8'
  hooks:
  - id: clang-format
    types_or: ["c", "c++"]
    stages: ["pre-commit"]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.9
  hooks:
  - id: ruff-format

exclude: '^tests/Baseline'
