# Copyright (c) 2025-now by the Zeek Project. See LICENSE for details.
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v20.1.8'
  hooks:
  - id: clang-format
    types_or: ["c", "c++"]
    stages: ["pre-commit"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    stages: ["pre-commit"]
  - id: check-added-large-files

- repo: https://gitlab.com/daverona/pre-commit/cpp
  rev: 0.8.0
  hooks:
  - id: cpplint
    exclude: '3rdparty/'
    args: ["--quiet"]
    stages: ["pre-commit"]

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
    stages: ["pre-commit"]
  - id: cmake-lint
    stages: ["pre-commit"]

- repo: https://github.com/crate-ci/typos
  rev: v1.35.4
  hooks:
  - id: typos

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.9
  hooks:
  - id: ruff
    args: [ --fix ]
  - id: ruff-format

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.45.0
  hooks:
    - id: markdownlint-fix

exclude: '^tests/Baseline'
