# Copyright (c) 2025-now by the Zeek Project. See LICENSE for details.
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v20.1.8'
  hooks:
  - id: clang-format
    types_or: ["c", "c++"]
    stages: ["pre-commit"]

- repo: https://gitlab.com/daverona/pre-commit/cpp
  rev: 0.8.0
  hooks:
  - id: cpplint
    exclude: '3rdparty/'
    args: ["--quiet"]
    stages: ["pre-commit"]

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
    stages: ["pre-commit"]
  - id: cmake-lint
    stages: ["pre-commit"]

exclude: '^tests/Baseline'
